name: Indexer

on:
  schedule:
    - cron: "0 * * * *" 
  workflow_dispatch:

jobs:
  index-events:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install
      - name: Run indexer
        run: npm run start
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
          PROXY_ADDRESS: ${{ secrets.PROXY_ADDRESS }}
