name: Run Listener

on:
  schedule:
    - cron: "0 * * * *" # every hour
  workflow_dispatch:

jobs:
  indexer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Create .env file
        run: |
          echo "RPC_URL=${{ secrets.RPC_URL }}" >> .env
          echo "PROXY_ADDRESS=${{ secrets.PROXY_ADDRESS }}" >> .env

      - name: Run Listener
        run: npm run start
